import { AudioWaveform,BrainCircuit,Building2,FileSearch,Image,Lock,Mail,Video } from "lucide-react";import toast from "react-hot-toast";import { Card,Panel,SectionTitle } from "../../components/ui/Shared";import { modelSlots } from "../../data/mockData";
export function Features(){const features=[[Image,"Image deepfake detection","GAN artifact detection, fake image classification, metadata review, and image report generation."],[Video,"Video forensic timeline","Frame sampling, temporal inconsistency detection, segment-level risk scoring, and timeline charts."],[AudioWaveform,"Voice authenticity analysis","Synthetic speech probability, waveform view, voiceprint score, replay risk, and audio artifact indicators."],[FileSearch,"Case reports","Unified report cards for analysts, reviewers, and security teams."],[BrainCircuit,"Model lab","Model slots for Hugging Face, custom models, ensembles, and future AI service integration."],[Lock,"Audit trail","Track analysis actions, reviewer notes, case status, and platform events."]];return <main className="mx-auto max-w-7xl px-4 py-12"><SectionTitle eyebrow="Features" title="Everything needed for multimodal authenticity review"/><div className="grid gap-6 sm:grid-cols-2 xl:grid-cols-3">{features.map(([Icon,title,text]:any)=><Card key={title} className="p-6"><Icon className="text-guard-cyan"/><h3 className="mt-5 text-2xl font-black">{title}</h3><p className="mt-3 text-slate-400">{text}</p></Card>)}</div></main>}
export function UseCases(){const cases=[["Newsroom verification","Check suspicious images, interviews, and leaked clips before publication."],["Financial fraud prevention","Detect voice cloning and fake identity evidence in scam cases."],["Political misinformation response","Prioritize high-risk manipulated media for human review."],["Enterprise security","Monitor audio/video impersonation and suspicious profile media."],["Research and education","Demonstrate how multimodal AI forensics workflows are structured."],["Legal evidence triage","Produce preliminary media authenticity reports and audit history."]];return <main className="mx-auto max-w-7xl px-4 py-12"><SectionTitle eyebrow="Use cases" title="Designed for investigators, reviewers, and digital trust teams"/><div className="grid gap-6 md:grid-cols-2 xl:grid-cols-3">{cases.map(([title,text])=><Card key={title} className="p-6"><Building2 className="text-guard-cyan"/><h3 className="mt-5 text-2xl font-black">{title}</h3><p className="mt-3 text-slate-400">{text}</p></Card>)}</div></main>}
export function Models(){return <main className="mx-auto max-w-7xl px-4 py-12"><SectionTitle eyebrow="Models" title="Model slots from the three original AI projects" text="Image, video, and voice model slots are unified into one model lab concept."/><div className="grid gap-5 lg:grid-cols-2">{modelSlots.map((model)=><Card key={model.id} className="p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div><p className="text-2xl font-black">{model.name}</p><p className="mt-1 text-slate-400">{model.provider}</p></div><span className="h-fit rounded-full bg-guard-cyan/10 px-3 py-1 text-sm font-black text-guard-cyan">{model.status}</span></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-white/5 p-4"><p className="text-sm text-slate-400">Module</p><p className="font-black capitalize">{model.module}</p></div><div className="rounded-2xl bg-white/5 p-4"><p className="text-sm text-slate-400">Accuracy</p><p className="font-black text-guard-green">{model.accuracy}%</p></div><div className="rounded-2xl bg-white/5 p-4"><p className="text-sm text-slate-400">Latency</p><p className="font-black">{model.latency}</p></div></div></Card>)}</div></main>}
export function Pricing(){const plans=[["Starter","$0","Portfolio demo, local mock results, public dashboard."],["Investigator","$29","Case review workflow, reports, audit trail, model lab."],["Enterprise","Custom","API gateway, real AI microservices, role permissions, deployment support."]];return <main className="mx-auto max-w-7xl px-4 py-12"><SectionTitle eyebrow="Pricing" title="Flexible plans for AI media verification teams"/><div className="grid gap-6 lg:grid-cols-3">{plans.map(([name,price,text],i)=><Card key={name} className={`p-6 ${i===1?"border-guard-cyan":""}`}><h3 className="text-3xl font-black">{name}</h3><p className="mt-4 text-5xl font-black text-guard-cyan">{price}</p><p className="mt-4 text-slate-400">{text}</p><button className="guard-button mt-6 w-full">Choose plan</button></Card>)}</div></main>}
export function Docs(){return <main className="mx-auto max-w-5xl px-4 py-12"><SectionTitle eyebrow="Docs" title="API-ready architecture" text="TruthGuard AI is delivered as a frontend-first unified platform with clear future backend integration points."/><Panel className="p-6"><h3 className="text-2xl font-black">Suggested full-stack architecture</h3><pre className="mt-5 overflow-auto rounded-2xl bg-black p-5 text-sm text-slate-200">{`client/
  React + TypeScript + Vite
server/
  Express API Gateway
  /api/image/analyze
  /api/video/analyze
  /api/voice/analyze
ai-services/
  image-service/
  video-service/
  audio-service/`}</pre></Panel></main>}
export function Contact(){return <main className="mx-auto max-w-4xl px-4 py-12"><SectionTitle eyebrow="Contact" title="Request an AI forensics platform demo"/><Panel className="p-6"><div className="grid gap-4 sm:grid-cols-2"><input className="guard-input" placeholder="Name"/><input className="guard-input" placeholder="Email"/><select className="guard-input"><option>Image + Video + Voice platform</option><option>Image detection only</option><option>Voice fraud detection</option></select><input className="guard-input" placeholder="Organization"/><textarea className="guard-input h-36 sm:col-span-2" placeholder="Message"/></div><button onClick={()=>toast.success("Demo request sent")} className="guard-button mt-5"><Mail size={18}/> Send Request</button></Panel></main>}
